const data = {
  products: [
    {
      // _id: '1',
      name: 'Black Forest',
      slug: 'black-forest-cake',
      category: 'Cake',
      image: './img/cake/black-forest.jpg',
      price: 300,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: 'Delicious black forest cake with toppins',
    },
    {
      // _id: '2',
      name: 'Choco Truffle',
      slug: 'choco-truffle-cake',
      category: 'Cake',
      image: './img/cake/Chocolate-Truffle.jpg',
      price: 400,
      countInStock: 9,
      rating: 4.6,
      numReviews: 12,
      description: 'Delicious choco truffle cake with toppins',
    },

    {
      // _id: '3',
      name: 'Butterscotch',
      slug: 'butter-scotch-cake',
      category: 'Cake',
      image: './img/cake/Butterscotch-Cake.jpg',
      price: 450,
      countInStock: 15,
      rating: 4.9,
      numReviews: 19,
      description: 'Delicious butterscotch cake with toppins',
    },
    {
      // _id: '4',
      name: 'Chocolate',
      slug: 'chocolate-cake',
      category: 'Cake',
      image: './img/cake/Chocolate-Truffle.jpg',
      price: 350,
      countInStock: 5,
      rating: 4,
      numReviews: 7,
      description: 'Delicious chocolate cake with toppins',
    },
    {
      name: 'Mango Mousse',
      slug: 'mango-mousse',
      category: 'Mousse',
      image: './img/moouse/Mango-mousse.jpg',
      price: 50,
      countInStock: 7,
      rating: 4,
      numReviews: 8,
      description: 'Delicious mousse',
    },
    {
      name: 'Strawberry Mousse',
      slug: 'strawberry-mousse',
      category: 'Mousse',
      image: './img/moouse/Strawberry-Mousse.jpg',
      price: 60,
      countInStock: 10,
      rating: 4.2,
      numReviews: 10,
      description: 'Delicious mousse',
    },
    {
      name: 'Pineapple Mousse',
      slug: 'pineapple-mousse',
      category: 'Mousse',
      image: './img/moouse/pineapple.jpg',
      price: 45,
      countInStock: 5,
      rating: 4.5,
      numReviews: 15,
      description: 'Delicious mousse',
    },
    {
      name: 'Maida Bread',
      slug: 'maida-bread',
      category: 'Bread',
      image: './img/bread/maida.jpg',
      price: 20,
      countInStock: 15,
      rating: 4.8,
      numReviews: 20,
      description: 'Bread',
    },
    {
      name: 'Wheat Bread',
      slug: 'wheat-bread',
      category: 'Bread',
      image: './img/bread/wheat.jpg',
      price: 25,
      countInStock: 20,
      rating: 4.9,
      numReviews: 24,
      description: 'Bread',
    },
    {
      name: 'Brownie',
      slug: 'brownie',
      category: 'Brownie',
      image: './img/brownie/brownie.jpg',
      price: 15,
      countInStock: 15,
      rating: 5,
      numReviews: 25,
      description: 'Brownie',
    },
    {
      name: 'Chocolate Cupcake',
      slug: 'chocolate-cupcake',
      category: 'Cupcake',
      image: './img/cupcakes/chocolate.jpg',
      price: 10,
      countInStock: 20,
      rating: 4.6,
      numReviews: 15,
      description: 'Cupcake',
    },
    {
      name: 'Vanilla Cupcake',
      slug: 'vanilla-cupcake',
      category: 'Cupcake',
      image: './img/cupcakes/istockphoto-610648924-612x612.jpg',
      price: 10,
      countInStock: 15,
      rating: 4.4,
      numReviews: 13,
      description: 'Cupcake',
    },
  ],
};
export default data;
